### ISSUE TITLE
Wire diagram release?

### ISSUE THREAD

**Issue by The-Lord-of-Owls** [X360Tools/PicoRGH#4]
while I'm sure with some trial and error one could figure it out on their own, it would save alot of time and likely prevent damaged systems trying to use this if there were a diagram added for wiring this up.

**Comment by The-Lord-of-Owls** [comment]
![image](https://user-images.githubusercontent.com/119661891/233502318-4c8f8e51-6372-4dcd-ab97-793ac88228e3.png)
So far with a little help from a few people on discord I've managed to figure out that:
Green wire is for the PLL_BYPASS
White wire is for CPU_RESET
Black wire is for GRD and 3v3_EN(I'm curious why these two are bridged)
Red wire is for 3v3_OUT

But the wire connected to GPIO_15 has me confused. I am almost sure it goes to POST, judging by the stuff written in glitch.pio, but at this point I think I'm at a actual roadblock. I've not touched assembly in a couple years, and I'm pretty sure thats what glitch.pio is.

While this means I now know the wiring format, I don't understand what that section of the project is actually doing

**Comment by chackAJMCPE** [comment]
Hey the green wire cannot be PLL_BYPASS, this can be SMC_PLL

EDIT: What was i thinking year ago XD. This cannot be SMC_PLL.

**Comment by The-Lord-of-Owls** [comment]
I'll keep that in mind on the next trinity I work on. guess that's the only wire I had wrong then

**Comment by sangrin** [comment]
Any luck on that? I still don't understand why he uses 3.3_out to power the pico and not vsys. And I thought the green wire was PLL too. Guess i'm far behind than you.

**Comment by chackAJMCPE** [comment]
It can also be fake. Those wires that goes onto back of the console from jtag port are i2c pins. Theyre used is rgh2. Bruh.

EDIT: Those are NAND reader wires, not I2C

**Comment by The-Lord-of-Owls** [comment]
> Any luck on that? I still don't understand why he uses 3.3_out to power the pico and not vsys. And I thought the green wire was PLL too. Guess i'm far behind than you.

It's been a while since I've looked at this, but looking back at my screenshot, it looks to me that the 2nd set of wires going towards the back are not the same wires as the ones going under the board. If I had to guess it would be for something unrelated to the pico glitching.

The use of 3.3_out might be due to something specific with the pico itself. I'm a little hazy on the differance between the two pins but it looks like it does something that the vsys doesn't do maybe https://www.farnell.com/datasheets/3759470.pdf

**Comment by MichaelK-F** [comment]
It would be greatly appreciated if a simple wiring diagram (in fact, a few lines of text stating where the wires would go is just as good) would be released
@balika011 (yes I know RGH3 is better but my trinity console is not co-operating and I have been recommended to try a different RGH method and since I have a few RiPi picos I would like to get this method working)

**Comment by MichaelK-F** [comment]
> It can also be fake. Those wires that goes onto back of the console from jtag port are i2c pins. Theyre used is rgh2. Bruh.

I think the i2c pins are used because they are high speed (compared to the other pins).

**Comment by chackAJMCPE** [comment]
Pinout:
GPIO15 - POST
GPIO12 - CPU_PLL_BYPASS
GPIO11 - CPU_RESET
GND - GND
3V3 - 3V3
If someone doesn't have a compiled UF2 file then you can download it there: https://www.mediafire.com/file/1fizlyf6o8ztuf6/PicoRGH.uf2/file
Tell me if this works.

**Comment by chackAJMCPE** [comment]
> Any luck on that? I still don't understand why he uses 3.3_out to power the pico and not vsys. And I thought the green wire was PLL too. Guess i'm far behind than you.

VSYS is 5V input. 5V on Xbox 360 is always on. and we don't need for our rpi pico to waste power and heat up. So we use 3V3_OUT (its also an input) to power it (because Xbox 360 powers 3V3 line after you click power button).

**Comment by chackAJMCPE** [comment]
> > It can also be fake. Those wires that goes onto back of the console from jtag port are i2c pins. Theyre used is rgh2. Bruh.
> 
> I think the i2c pins are used because they are high speed (compared to the other pins).

CPU_RST pulse is WAY FASTER than I2C + I was wrong. this is not I2C. Those are NAND reader wires.

**Comment by chackAJMCPE** [comment]
> It would be greatly appreciated if a simple wiring diagram (in fact, a few lines of text stating where the wires would go is just as good) would be released @balika011 (yes I know RGH3 is better but my trinity console is not co-operating and I have been recommended to try a different RGH method and since I have a few RiPi picos I would like to get this method working)

Here it is: 
GPIO15 - POST
GPIO12 - CPU_PLL_BYPASS
GPIO11 - CPU_RESET
GND - GND
3V3 - 3V3
and download the UF2 here: https://www.mediafire.com/file/1fizlyf6o8ztuf6/PicoRGH.uf2/file

**Comment by anthonyg45157** [comment]
> > It would be greatly appreciated if a simple wiring diagram (in fact, a few lines of text stating where the wires would go is just as good) would be released @balika011 (yes I know RGH3 is better but my trinity console is not co-operating and I have been recommended to try a different RGH method and since I have a few RiPi picos I would like to get this method working)
> 
> Here it is: GPIO15 - POST GPIO12 - CPU_PLL_BYPASS GPIO11 - CPU_RESET GND - GND 3V3 - 3V3 and download the UF2 here: https://www.mediafire.com/file/1fizlyf6o8ztuf6/PicoRGH.uf2/file

Please let me know if you would like to work on this further and best way to contact .Apparently it is not working as is. Another user tried, I have not yet. 

Also the Pico 2 was announced a couple days ago and that might be a more reliable glitch chip. Only time will tell but I'm highly interested in assisting in testing/compiling.

**Comment by quimodotcom** [comment]
![diagramfalcon](https://github.com/user-attachments/assets/5713c46e-f564-4d71-956b-307d05136021)

made this quickly. doesnt show console points, but refer to rgh3 points for that as theres a lot of ref pics for that.

**Comment by The-Lord-of-Owls** [comment]
Thank you so much for the assistance, this has been a big help

**Comment by chackAJMCPE** [comment]
> Thank you so much for the assistance, this has been a big help

Did you suceed? Did it boot?
